parameters:
- name: location
  displayName: "Azure region"
  type: string
  default: 'eastus'

- name: customer_client_id
  displayName: "Customer Client ID"
  type: string
  default: "857530e9-0b30-421c-b00b-815a801fac72"

- name: customer_client_secret
  displayName: "Customer Client Secret"
  type: string
  default: "6Lw8Q~WP-ad0lNh.NetL8mhr3seGK~VWUnxaOaHh"
  
- name: customer_tenant_id
  displayName: "Customer Tenant ID"
  type: string
  default: "67e121b7-8bbd-4f33-a75e-333e1049d85f"

- name: customer_subscription_id
  displayName: "Customer Subscription ID"
  type: string
  default: "f58fa3a0-e890-4321-b6c5-22da5adc8d94"
  
- name: default_domain_name
  displayName: "Default Domain Name"
  type: string
  default: "ehabmoghazihotmail"

- name: customer_subscription_owner_first_name
  displayName: "Subscription Owner First Name"
  type: string
  default: "devops"
# - name: customer_subscription_owner_last_name 
#   displayName: "Subscription Owner Last Name"
#   type: string
#   default: "sh"

stages:
- stage: TerraformRun
  displayName: 'Terraform Run'
  pool:
    vmImage: ubuntu-latest
  jobs:
    - job: TerraformJob
      displayName: 'Terraform Job'
      steps:
        - script: |
            echo "Location: ${{ parameters.location }}"
            dateYMD=$(date +%Y%m%dT%H%M%S%NZ)
            workspace=my_workspace_${dateYMD}
            echo $dateYMD

            terraform workspace new $workspace
            terraform init

            terraform plan \
              -var customer_subscription_id=${{ parameters.customer_subscription_id }} \
              -var customer_client_id=${{ parameters.customer_client_id}} \
              -var customer_tenant_id=${{ parameters.customer_tenant_id }} \
              -var customer_client_secret=${{ parameters.customer_client_secret }} \
              -var location=${{ parameters.location }} \
              -var domain_name=${{parameters.default_domain_name}} \
              -var customer_subscription_owner_first_name=${{parameters.customer_subscription_owner_first_name}} \
              -var customer_subscription_owner_last_name=$(date +%S%3N)

            terraform apply --auto-approve \
              -var customer_subscription_id=${{ parameters.customer_subscription_id }} \
              -var customer_client_id=${{ parameters.customer_client_id}} \
              -var customer_tenant_id=${{ parameters.customer_tenant_id }} \
              -var customer_client_secret=${{ parameters.customer_client_secret }} \
              -var location=${{ parameters.location }} \
              -var domain_name=${{parameters.default_domain_name}} \
              -var customer_subscription_owner_first_name=${{parameters.customer_subscription_owner_first_name}} \
              -var customer_subscription_owner_last_name=$(date +%S%3N) 

            owner_password=$(terraform output "customer_subscription_owner_password" | sed 's/^"//;s/"$//')     
            echo "Owner Password: $owner_password"
            owner_principal=$(terraform output "user_principal_name" | sed 's/^"//;s/"$//')
            echo "Owner Principal: $owner_principal"
            echo "##vso[task.setvariable variable=password;isOutput=true]$owner_password"
            echo "##vso[task.setvariable variable=principal;isOutput=true]$owner_principal"
          name: setVariables
